version: '3.7'

services:
  bot:
    build:
      context: .
      target: 'develop-stage'
    volumes:
      - type: bind
        source: ./
        target: /app
      - cargo-cache:/usr/local/cargo/registry
      - target-cache:/app/target
    command: /bin/sh -c "cargo watch -x run"
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - GOOGLE_APPLICATION_CREDENTIALS=${GOOGLE_APPLICATION_CREDENTIALS}
      - RUST_BACKTRACE=1

volumes:
  cargo-cache:
  target-cache:
